DROP TABLE IF EXISTS STATE;
CREATE TABLE STATE (
id varchar(2048) primary key,
linkKey varchar(2048),
sourceName varchar(256),
sourceType varchar(256),
managedEntityChain varchar(2048),
managedNodeChain varchar(2048),
cleared boolean,
severity varchar(20),
stateDescr varchar(255),
shortDescr varchar(1024),
descr varchar(2048),
count bigint,
categories varchar(1024),
isRoot boolean,
causedBy varchar(2048),
causes varchar(2048),
isConsumerView boolean,
isProviderView boolean,
aggregatedBy varchar(2048),
aggregates varchar(2048),
meLastUpdateTime bigint,
meFirstRaiseTime bigint,
meLastRaiseTime bigint,
meLastClearTime bigint,
lastUpdateTime bigint,
firstRaiseTime bigint,
lastRaiseTime bigint,
lastClearTime bigint,
specificProperties clob,
timestamp bigint);
